sudo: required

language: c

services:
  - docker

env:
  REPO=moxielogic/cfarm-test-libffi

before_install:
  - docker build -f Dockerfile --build-arg CFARM_TEST_LIBFFI_VERSION="$(git describe --tags --dirty=+)" -t $REPO:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $REPO:latest;
    fi
  - echo All done.
